# Generated by Django 3.1 on 2020-11-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201107_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='post content'),
        ),
    ]
