# Generated by Django 3.0.7 on 2020-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures/profiles', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('posts', models.PositiveIntegerField(default=0, verbose_name='posts made')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='comments made')),
                ('reputation', models.PositiveIntegerField(default=0, help_text='Score obtained from comments and votes received.', verbose_name='user reputation')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='moderator')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
