# Generated by Django 3.1 on 2020-11-01 00:43

from django.db import migrations, models
import django_extensions.db.fields
import profiles.models.profiles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='user')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('birthday', models.DateField(null=True, validators=[profiles.models.profiles.validate_birthday])),
                ('is_moderator', models.BooleanField(default=False)),
                ('reputation', models.PositiveIntegerField(default=0, help_text='Score obtained from posts and comments made, and votes received.', verbose_name='user reputation')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
