# Generated by Django 3.1 on 2020-09-06 05:19

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, validators=[profiles.models.validate_birthday]),
        ),
    ]
