# Generated by Django 3.1 on 2020-09-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_summary_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary_reports',
        ),
    ]
