# Generated by Django 3.1 on 2020-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200818_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary_reports',
            field=models.CharField(choices=[('', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='', help_text='Set how often the summary report is obtained', max_length=1, verbose_name='Summary report interval'),
        ),
    ]
