version: '3'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  django: &django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.8.6

  celeryworker:
    <<: *django
    image: celeryworker
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty worker -l INFO

  celerybeat:
    <<: *django
    image: celerybeat
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty beat -l INFO