version: '3'

volumes:
  local_postgres_data: {}
  local_rabbitmq_data: {}

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  django: &django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.8.8
    environment:
      - RABBITMQ_USER=gonza56d
      - RABBITMQ_PASSWORD=abc123abc123
      - NODE_IP_ADDRESS=127.0.0.1
    volumes:
      - local_rabbitmq_data:/var/lib/rabbitmq/data
    env_file:
      - ./.envs/.rabbitmq

  celeryworker:
    <<: *django
    image: pyrty_celeryworker
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A taskapp.tasks worker -l INFO

  celerybeat:
    <<: *django
    image: pyrty_celerybeat
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A taskapp.tasks beat -l INFO