version: '3'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.8.8

  flower:
    <<: *django
    image: pyrty_local_flower
    ports:
      - "5555:5555"
    command: celery flower -A pyrty --broker="amqp://rabbitmq:5672"

  celeryworker:
    <<: *django
    image: pyrty_local_celeryworker
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty worker -l info

  celerybeat:
    <<: *django
    image: pyrty_local_celerybeat
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty beat -l info