version: '3'

volumes:
  production_postgres_data: {}

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: gunicorn pyrty.wsgi
    volumes:
      - .:/app/
    depends_on:
      - postgres

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: pyrty_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  rabbitmq:
    image: rabbitmq:3.8.8

  flower:
    <<: *django
    image: pyrty_production_flower
    ports:
      - "5555:5555"
    command: celery flower -A pyrty --broker="amqp://rabbitmq:5672"

  celeryworker:
    <<: *django
    image: pyrty_production_celeryworker
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty worker -l info

  celerybeat:
    <<: *django
    image: pyrty_production_celerybeat
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: celery -A pyrty beat -l info