# Generated by Django 3.0.7 on 2020-06-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, verbose_name='subforum title')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
            ],
            options={
                'unique_together': {('forum', 'name')},
            },
        ),
    ]
