# Generated by Django 3.1 on 2020-09-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subforums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subforum',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
    ]
