# Generated by Django 3.1 on 2020-09-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subforums', '0002_auto_20200910_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subforum',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
    ]
