# Generated by Django 3.1 on 2020-09-10 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='negative_votes',
            field=models.ManyToManyField(related_name='c_negative_vote_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='positive_votes',
            field=models.ManyToManyField(related_name='c_positive_vote_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
