# Generated by Django 3.0.7 on 2020-06-20 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_auto_20200615_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users_negative_votes',
            field=models.ManyToManyField(null=True, related_name='users_negative_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='users_positive_votes',
            field=models.ManyToManyField(null=True, related_name='users_positive_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
