# Generated by Django 3.0.7 on 2020-06-20 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_auto_20200620_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users_negative_votes',
            field=models.ManyToManyField(related_name='users_negative_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='users_positive_votes',
            field=models.ManyToManyField(related_name='users_positive_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
