# Generated by Django 3.0.7 on 2020-07-23 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privatemessages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='origin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_origin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
