# Generated by Django 3.0.7 on 2020-06-26 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_messages', '0002_auto_20200621_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='to_user',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='origin_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_origin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='target_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='message_target', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
