# Generated by Django 3.0.7 on 2020-06-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0003_auto_20200625_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
